only_rules:
  - force_cast
  - force_try
  - force_unwrapping
  - implicitly_unwrapped_optional
  - unused_optional_binding
  - duplicate_conditions
included:
  - packages/modules/narduk-logging/swift
