/**
 * `@narduk-enterprises/geogrid-web/color` — the canonical Narduk ramp engine.
 *
 * One ramp model, one sampler, one rounding rule, shared by every renderer in
 * the estate. The reference implementation is narduk-data
 * `shared/colorramp.py`; this module is its TypeScript twin and is asserted
 * byte-exact against bytes that engine produced (`tests/fixtures/ramp-parity-v1.json`,
 * regenerated by the `generate_ramp_parity.py` beside it).
 *
 * The model in one line: **stops carry a normalized position in `0…1` and 8-bit
 * RGBA channels, and interpolation rounds half to even.**
 *
 * Catalog wire stops do not arrive in that model — they carry raw data values —
 * so {@link normalizeWireStops} is the front door for anything read out of
 * `catalog.json`.
 *
 * ```ts
 * import { normalizeWireStops, rampLut, sampleRampValue } from '@narduk-enterprises/geogrid-web/color'
 *
 * const stops = normalizeWireStops(dataset.ramp, dataset.valueRange, dataset.scale)
 * const lut = rampLut(stops)                    // 1024 bytes, straight to texImage2D
 * const rgba = sampleRampValue(stops, 0.257, dataset.valueRange, dataset.scale)
 * ```
 *
 * This subpath is deliberately **not** re-exported from the package root: the
 * root barrel still carries the deprecated `core` spellings of `normalizeValue`
 * and `rampLut`, which mean different things. Import `./color` explicitly and
 * there is no ambiguity about which engine you got.
 */
export type { RampStop } from '../core/models.js'
export {
  denormalizePosition,
  normalizeValue,
  toValueRangeTuple,
  type ValueRangeInput,
} from './normalize.js'
export {
  normalizeWireStops,
  rampLut,
  roundHalfToEven,
  sampleRamp01,
  sampleRampValue,
  type NormalizeWireStopsOptions,
  type RampStopWire,
  type RGBA8,
  type WireStopDomain,
} from './ramp.js'
