import type { AppVisibility } from './types.js'

const workflowSha = '9070db7244649bf192d392a5b96eb1656997c84c'

// Resolved from fleet's organization routes. Creating files does not grant
// selected-repository membership; onboarding remains an explicit fleet action.
const linuxRoute =
  '{"group":"linux-ci","labels":["self-hosted","Linux","X64","proxmox","linux-ci"]}'
const browserRoute =
  '{"group":"playwright-isolated","labels":["self-hosted","Linux","X64","proxmox-playwright-x64"]}'

function setupSteps(): string[] {
  return [
    '      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0',
    '        with:',
    '          persist-credentials: false',
    '      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9',
    '        with:',
    '          version: 10.33.4',
    '          dest: ${{ runner.temp }}/setup-pnpm',
    '      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0',
    '        with:',
    '          node-version: 22.22.3',
    '          package-manager-cache: false',
    '      - name: Install workspace',
    '        env:',
    '          GH_PACKAGES_READ: ${{ secrets.NARDUK_PLATFORM_GH_PACKAGES_READ }}',
    '        run: |',
    '          set -euo pipefail',
    '          test -n "$GH_PACKAGES_READ"',
    '          umask 077',
    '          auth_file="$(mktemp "${RUNNER_TEMP}/npmrc-auth.XXXXXX")"',
    '          trap \'rm -f "$auth_file"\' EXIT',
    '          printf \'//npm.pkg.github.com/:_authToken=%s\\n\' "$GH_PACKAGES_READ" > "$auth_file"',
    '          NPM_CONFIG_USERCONFIG="$auth_file" NPM_CONFIG_GLOBALCONFIG=/dev/null pnpm install --frozen-lockfile',
  ]
}

export function createCiWorkflow(visibility: AppVisibility): string {
  const header = [
    'name: CI',
    '',
    'on:',
    '  push:',
    '    branches: [main]',
    '  pull_request:',
    '',
    'concurrency:',
    '  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}',
    '  cancel-in-progress: true',
    '',
    'permissions:',
    '  contents: read',
    '',
    'jobs:',
  ]
  if (visibility === 'private') {
    return [
      ...header,
      '  # Before the first run, onboard this repository into both fleet groups.',
      '  # These routes do not grant selected-repository membership themselves.',
      '  ci:',
      `    uses: narduk-enterprises/workflows/.github/workflows/nuxt-cloudflare.yml@${workflowSha}`,
      '    permissions:',
      '      contents: read',
      '      packages: read',
      '    with:',
      `      runner: '${linuxRoute}'`,
      "      node-version: '22.22.3'",
      '      package-manager: pnpm',
      '      require-scripts: true',
      '      typecheck-worker-script: typecheck',
      "      typecheck-web-script: ''",
      '      build-script: build',
      "      extra-scripts: 'format:check lint knip'",
      '      run-tests: true',
      '      test-script: test:unit',
      '      run-e2e: true',
      '      e2e-script: test:e2e',
      `      e2e-runner: '${browserRoute}'`,
      '      e2e-shards: 3',
      "      e2e-args: '--project=chromium --workers=1'",
      '      e2e-install-browsers: false',
      '      # The guest exports its immutable browser path; no caller override.',
      '    secrets:',
      '      NARDUK_PLATFORM_GH_PACKAGES_READ: ${{ secrets.NARDUK_PLATFORM_GH_PACKAGES_READ }}',
      '',
    ].join('\n')
  }
  // Public callers cannot call the private shared workflow. Keep all three
  // browser shards hosted and require their merged evidence before acceptance.
  return [
    ...header,
    '  quality:',
    '    name: Static, unit, and build',
    '    runs-on: ubuntu-24.04',
    '    timeout-minutes: 30',
    '    env:',
    '      NODE_OPTIONS: --max-old-space-size=3072',
    '    steps:',
    ...setupSteps(),
    '      - run: pnpm run quality:static',
    '',
    '  browser:',
    '    name: Chromium shard ${{ matrix.shard }}/3',
    '    needs: quality',
    '    strategy:',
    '      fail-fast: false',
    '      max-parallel: 3',
    '      matrix:',
    '        shard: [1, 2, 3]',
    '    runs-on: ubuntu-24.04',
    '    timeout-minutes: 30',
    '    env:',
    '      NODE_OPTIONS: --max-old-space-size=3072',
    '      PLAYWRIGHT_HTML_OPEN: never',
    '    steps:',
    ...setupSteps(),
    '      - name: Install Chromium on the hosted runner',
    '        run: pnpm exec playwright install --with-deps chromium',
    '      - name: Build application',
    '        run: pnpm run build',
    '      - name: Run Chromium shard',
    '        run: pnpm run test:e2e --project=chromium --shard=${{ matrix.shard }}/3 --workers=1 --reporter=line,blob',
    '      - name: Upload shard blob report',
    '        if: always()',
    '        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1',
    '        with:',
    '          name: blob-${{ github.run_id }}-${{ github.run_attempt }}-chromium-${{ matrix.shard }}',
    '          path: blob-report',
    '          retention-days: 1',
    '          if-no-files-found: error',
    '',
    '  browser-report:',
    '    name: Merge Playwright reports',
    "    if: always() && needs.quality.result == 'success'",
    '    needs: [quality, browser]',
    '    runs-on: ubuntu-24.04',
    '    timeout-minutes: 20',
    '    env:',
    '      PLAYWRIGHT_HTML_OPEN: never',
    '    steps:',
    ...setupSteps(),
    "      - name: Download this run's shard reports",
    '        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1',
    '        with:',
    '          pattern: blob-${{ github.run_id }}-${{ github.run_attempt }}-chromium-*',
    '          path: all-blob-reports',
    '          merge-multiple: true',
    '      - name: Require all three shard reports',
    '        run: |',
    '          set -euo pipefail',
    "          test \"$(find all-blob-reports -maxdepth 1 -name '*.zip' | wc -l | tr -d ' ')\" = 3",
    '      - name: Merge reports and traces',
    '        run: pnpm exec playwright merge-reports --reporter=html all-blob-reports',
    '      - name: Upload merged browser diagnostics',
    '        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1',
    '        with:',
    '          name: playwright-report-${{ github.run_id }}-${{ github.run_attempt }}',
    '          path: playwright-report',
    '          retention-days: 14',
    '          if-no-files-found: error',
    '',
    '  Required:',
    '    name: ci / Required',
    '    if: always()',
    '    needs: [quality, browser, browser-report]',
    '    runs-on: ubuntu-24.04',
    '    timeout-minutes: 5',
    '    steps:',
    '      - name: Require static and browser success',
    '        env:',
    '          QUALITY_RESULT: ${{ needs.quality.result }}',
    '          BROWSER_RESULT: ${{ needs.browser.result }}',
    '          REPORT_RESULT: ${{ needs.browser-report.result }}',
    '        run: |',
    '          set -euo pipefail',
    '          test "$QUALITY_RESULT" = success',
    '          test "$BROWSER_RESULT" = success',
    '          test "$REPORT_RESULT" = success',
    '',
  ].join('\n')
}
