import type { GridBBox } from '../core/models.js'

/**
 * Web-Mercator tile geometry, ported from GeoGridKit
 * `Sources/GeoGridRender/GridTileMath.swift`.
 *
 * The port is literal on purpose. Both renderers bake tiles for the same
 * datasets, and a tile whose pixel centers land half a pixel off the Swift
 * renderer's is not a rounding difference — it is two clients disagreeing about
 * where the coastline is, at every zoom, forever. The Swift values are pinned in
 * `tests/fixtures/tile-math-parity-v1.json`, generated by calling GeoGridKit
 * itself (`tests/fixtures/generate_tile_math_parity.sh`), so this file is
 * asserted against Swift's doubles rather than against its own arithmetic.
 *
 * Conventions, all shared with GeoGridKit:
 *
 * - `side` is the tile's **pixel** side, not its point side. A `@2x` request is
 *   a 512-pixel tile at the same `z/x/y`, and {@link GridTileKey} carries that
 *   512 — which is why {@link lonLatForTilePixel} never sees a scale factor.
 * - Pixel `(0, 0)` is the tile's top-left **corner**; a pixel *center* is
 *   `(column + 0.5, row + 0.5)`, which {@link lonLatForTilePixelCenter} applies.
 * - `y` and `pixelY` grow southward, matching the tile scheme and the row order
 *   of a `/grid` payload.
 */

/** Matches GeoGridKit `GridTileKey`. `side` is the output's pixel side. */
export interface GridTileKey {
  z: number
  x: number
  y: number
  side: number
}

/** A geographic point, in degrees. Matches GeoGridKit `GridTileMath.Coordinate`. */
export interface GridTileCoordinate {
  longitude: number
  latitude: number
}

/** The latitude Web Mercator cuts off at — `bounds` of the `z0` tile. */
export const WEB_MERCATOR_MAX_LATITUDE = 85.05112877980659

function isFiniteTile(tile: GridTileKey): boolean {
  return (
    Number.isFinite(tile.z) &&
    Number.isFinite(tile.x) &&
    Number.isFinite(tile.y) &&
    Number.isFinite(tile.side) &&
    tile.side > 0
  )
}

/**
 * The lon/lat of a point inside a tile, in **pixel** coordinates.
 *
 * `null` for a degenerate tile or a non-finite probe, exactly where the Swift
 * `guard` returns nil. Note a negative `z` is clamped to `0` rather than
 * rejected — `pow(2, max(z, 0))` in the original — so the whole-world tile is
 * what an underflowing zoom draws.
 */
export function lonLatForTilePixel(
  tile: GridTileKey,
  pixelX: number,
  pixelY: number,
): GridTileCoordinate | null {
  if (!isFiniteTile(tile) || !Number.isFinite(pixelX) || !Number.isFinite(pixelY)) return null

  const tileCount = 2 ** Math.max(tile.z, 0)
  const tileOriginU = tile.x / tileCount
  const tileOriginV = tile.y / tileCount
  const tileSpan = 1 / tileCount
  const worldU = tileOriginU + (pixelX / tile.side) * tileSpan
  const worldV = tileOriginV + (pixelY / tile.side) * tileSpan
  return {
    longitude: worldU * 360 - 180,
    latitude: (Math.atan(Math.sinh(Math.PI * (1 - 2 * worldV))) * 180) / Math.PI,
  }
}

/** The lon/lat of the **center** of pixel `(column, row)`. */
export function lonLatForTilePixelCenter(
  tile: GridTileKey,
  column: number,
  row: number,
): GridTileCoordinate | null {
  return lonLatForTilePixel(tile, column + 0.5, row + 0.5)
}

/**
 * A tile's geographic extent as `[west, south, east, north]`.
 *
 * GeoGridKit answers with a `GeoBounds`; the tuple here is the same four numbers
 * in the order the rest of this package spells a {@link GridBBox}, and both are
 * built by ordering the two corners rather than assuming which is which.
 */
export function tileBounds(tile: GridTileKey): GridBBox | null {
  const topLeft = lonLatForTilePixel(tile, 0, 0)
  const bottomRight = lonLatForTilePixel(tile, tile.side, tile.side)
  if (!topLeft || !bottomRight) return null
  return [
    Math.min(topLeft.longitude, bottomRight.longitude),
    Math.min(topLeft.latitude, bottomRight.latitude),
    Math.max(topLeft.longitude, bottomRight.longitude),
    Math.max(topLeft.latitude, bottomRight.latitude),
  ]
}

/** Whether a tile's extent overlaps a grid's, so the tile can carry any data. */
export function tileIntersectsBBox(tile: GridTileKey, bbox: GridBBox): boolean {
  const bounds = tileBounds(tile)
  if (!bounds) return false
  const [tileWest, tileSouth, tileEast, tileNorth] = bounds
  const [west, south, east, north] = bbox
  return tileWest <= east && tileEast >= west && tileSouth <= north && tileNorth >= south
}

/**
 * The per-tile constants that turn a screen UV into a data UV.
 *
 * ## Why this is not just `lonLatForTilePixel` per pixel
 *
 * The GPU evaluates this in a fragment shader, in `highp float`, so every term
 * that can be evaluated once per tile is evaluated **here**, in double, and the
 * shader receives already-differenced constants:
 *
 * - Longitude is affine in the tile's x, and the bbox mapping is affine in
 *   longitude, so the whole of `u` collapses to `uOrigin + s * uSpan` — with no
 *   subtraction of similar magnitudes left for the GPU to do at all. This half
 *   is genuinely exact.
 * - Latitude is not affine, so `v` keeps one transcendental step, and its
 *   argument is pre-differenced: `mercArgOrigin + s * mercArgSpan` is exactly
 *   `π(1 - 2·worldV)`.
 *
 * ## What that buys, and what is honestly not known
 *
 * An earlier draft of this comment asserted a precise error budget, a precise
 * ranking against the naive form, and a named dominant term. Two independent
 * float32 simulations then disagreed on the last two, so what follows is
 * deliberately only what both agreed on.
 *
 * Worst registration error across a 256-pixel tile over a 4°-wide bbox,
 * simulating the shader in float32 against the double path — a range, because
 * two simulations produced values this far apart:
 *
 * | zoom | error |
 * |--|--|
 * | z12 | ~0.02 px |
 * | z15 | ~0.11–0.15 px |
 * | z18 | ~0.9–1.3 px |
 * | z20 | ~3.7–5.3 px |
 *
 * **Not established**, and deliberately no longer claimed here: whether this
 * form beats the naive `worldV = origin + s·span` at low zoom (one simulation
 * said it loses below ~z16, the other said it wins everywhere), and which
 * single operation dominates the error (one said the `mercArgOrigin + s·span`
 * addition, the other the `atan(sinh(…))` evaluation). Both are plausible;
 * float32 simulation has real freedom in per-operation rounding, FMA fusion and
 * constant folding, and **nothing in this package can execute GLSL**, so
 * neither simulation is the arbiter. Settling it needs a measurement in a real
 * WebGL2 context — GeoGridWeb#17, which is also why the shader was not
 * "improved" on the strength of a simulation.
 *
 * What is not in doubt is the part that matters: the error is a fraction of a
 * pixel through z15 and z15 is already far past the native resolution of any
 * estate grid, so none of this reaches a real layer. The CPU path
 * ({@link projectTileUv}) runs the identical formula in double and has no such
 * limit, which is what the parity test compares against.
 */
export interface TileProjection {
  /** Data `u` at screen `x = 0`, and `du/dx` across the tile. */
  uOrigin: number
  uSpan: number
  /** `π(1 - 2·worldV)` at screen `y = 0`, and its derivative across the tile. */
  mercArgOrigin: number
  mercArgSpan: number
  /** `north`, and `1 / (north - south)`, of the grid bbox. */
  latNorth: number
  latInvSpan: number
}

/**
 * Build the tile's projection constants against a grid's `bbox`.
 *
 * A degenerate bbox (zero or inverted span on either axis) has no invertible
 * mapping, so it yields `null` and the caller draws nothing — the same answer
 * the renderers give a degenerate value range.
 */
export function tileProjection(tile: GridTileKey, bbox: GridBBox): TileProjection | null {
  if (!isFiniteTile(tile)) return null
  const [west, south, east, north] = bbox
  if (![west, south, east, north].every((value) => Number.isFinite(value))) return null
  const lonSpan = east - west
  const latSpan = north - south
  if (!(lonSpan > 0) || !(latSpan > 0)) return null

  const tileCount = 2 ** Math.max(tile.z, 0)
  const tileSpan = 1 / tileCount
  const lonWest = (tile.x / tileCount) * 360 - 180
  const lonWidth = tileSpan * 360
  return {
    uOrigin: (lonWest - west) / lonSpan,
    uSpan: lonWidth / lonSpan,
    mercArgOrigin: Math.PI * (1 - (2 * tile.y) / tileCount),
    mercArgSpan: -2 * Math.PI * tileSpan,
    latNorth: north,
    latInvSpan: 1 / latSpan,
  }
}

/** A normalized position inside a grid's bbox. `0…1` is inside the grid. */
export interface TileDataUv {
  u: number
  v: number
}

/**
 * Data `u` for a screen `x`. Affine, so a whole tile row shares one multiply.
 */
export function tileColumnU(projection: TileProjection, screenU: number): number {
  return projection.uOrigin + screenU * projection.uSpan
}

/**
 * Data `v` for a screen `y` — the transcendental half, and the reason a CPU
 * tile loop hoists this out of its inner loop: every pixel in a tile row shares
 * one latitude, so a 256-wide tile does 256 `atan(sinh(…))` calls instead of
 * 65 536. The shader has no such luxury and pays per fragment, which is exactly
 * the trade a GPU is for.
 */
export function tileRowV(projection: TileProjection, screenV: number): number {
  const latitude =
    (Math.atan(Math.sinh(projection.mercArgOrigin + screenV * projection.mercArgSpan)) * 180) /
    Math.PI
  return (projection.latNorth - latitude) * projection.latInvSpan
}

/**
 * Screen UV (`0…1` across the tile) → data UV, in double.
 *
 * The exact CPU twin of the shader's `dataUv`, and the function the CPU tile
 * renderer samples through, so the two paths agree by construction rather than
 * by two people porting the same formula twice.
 */
export function projectTileUv(
  projection: TileProjection,
  screenU: number,
  screenV: number,
): TileDataUv {
  return { u: tileColumnU(projection, screenU), v: tileRowV(projection, screenV) }
}
