-- narduk:no-transaction
--
-- 0002_history_rollups.sql -- the continuous-aggregate ladder, 1m -> 15m -> 1h
-- -> 1d, and its refresh policies.
--
-- The directive on line 1 is load-bearing: `CREATE MATERIALIZED VIEW ... WITH
-- (timescaledb.continuous)` cannot run inside a transaction block. Without it
-- the runner would wrap this file in BEGIN/COMMIT and PostgreSQL would reject
-- every statement with an error that looks like a bug in the runner.
--
-- DELIBERATE DEVIATION from docs/04-data-model.md, stated here rather than
-- discovered later. docs/04 writes `avg(value) AS avg` at each level and chains
-- the levels. An average of averages is only correct when every bucket carries
-- the same number of points, which is exactly what a telemetry store cannot
-- promise: a vessel that drops off the air for forty minutes of an hour makes
-- the 1h `avg` of twenty 1m rows a lie about that hour. These views therefore
-- carry `sum_value` and `n` instead, and every level above 1m sums both -- so
-- `sum_value / n` is the exact mean at 15m, 1h and 1d, not an approximation of
-- one. The query builders in this package compute `avg` from those two columns;
-- consumers never see the difference except that the number is right.
--
-- APPLIED MIGRATIONS ARE IMMUTABLE. Add 000N+1; do not edit this file.

CREATE MATERIALIZED VIEW IF NOT EXISTS telemetry_numeric_1m
WITH (timescaledb.continuous) AS
  SELECT
    time_bucket(INTERVAL '1 minute', ts) AS bucket,
    vessel_id,
    series_id,
    count(*)         AS n,
    sum(value)       AS sum_value,
    min(value)       AS min_value,
    max(value)       AS max_value,
    last(value, ts)  AS last_value
  FROM telemetry_numeric
  GROUP BY 1, 2, 3
WITH NO DATA;

CREATE MATERIALIZED VIEW IF NOT EXISTS telemetry_numeric_15m
WITH (timescaledb.continuous) AS
  SELECT
    time_bucket(INTERVAL '15 minutes', bucket) AS bucket,
    vessel_id,
    series_id,
    sum(n)                    AS n,
    sum(sum_value)            AS sum_value,
    min(min_value)            AS min_value,
    max(max_value)            AS max_value,
    last(last_value, bucket)  AS last_value
  FROM telemetry_numeric_1m
  GROUP BY 1, 2, 3
WITH NO DATA;

CREATE MATERIALIZED VIEW IF NOT EXISTS telemetry_numeric_1h
WITH (timescaledb.continuous) AS
  SELECT
    time_bucket(INTERVAL '1 hour', bucket) AS bucket,
    vessel_id,
    series_id,
    sum(n)                    AS n,
    sum(sum_value)            AS sum_value,
    min(min_value)            AS min_value,
    max(max_value)            AS max_value,
    last(last_value, bucket)  AS last_value
  FROM telemetry_numeric_15m
  GROUP BY 1, 2, 3
WITH NO DATA;

CREATE MATERIALIZED VIEW IF NOT EXISTS telemetry_numeric_1d
WITH (timescaledb.continuous) AS
  SELECT
    time_bucket(INTERVAL '1 day', bucket) AS bucket,
    vessel_id,
    series_id,
    sum(n)                    AS n,
    sum(sum_value)            AS sum_value,
    min(min_value)            AS min_value,
    max(max_value)            AS max_value,
    last(last_value, bucket)  AS last_value
  FROM telemetry_numeric_1h
  GROUP BY 1, 2, 3
WITH NO DATA;

-- Refresh policies. `start_offset` is bounded on each level so a refresh never
-- rewrites the whole history, and `end_offset` keeps the refresh clear of the
-- bucket still being written.
SELECT add_continuous_aggregate_policy('telemetry_numeric_1m',
  start_offset => INTERVAL '2 hours',
  end_offset   => INTERVAL '1 minute',
  schedule_interval => INTERVAL '1 minute',
  if_not_exists => TRUE);

SELECT add_continuous_aggregate_policy('telemetry_numeric_15m',
  start_offset => INTERVAL '1 day',
  end_offset   => INTERVAL '15 minutes',
  schedule_interval => INTERVAL '15 minutes',
  if_not_exists => TRUE);

SELECT add_continuous_aggregate_policy('telemetry_numeric_1h',
  start_offset => INTERVAL '7 days',
  end_offset   => INTERVAL '1 hour',
  schedule_interval => INTERVAL '1 hour',
  if_not_exists => TRUE);

SELECT add_continuous_aggregate_policy('telemetry_numeric_1d',
  start_offset => INTERVAL '30 days',
  end_offset   => INTERVAL '1 day',
  schedule_interval => INTERVAL '1 hour',
  if_not_exists => TRUE);
