-- narduk:no-transaction
--
-- 0002_history_rollups.sql -- the continuous-aggregate ladder, 1m -> 15m -> 1h
-- -> 1d, and its refresh policies.
--
-- The directive on line 1 is load-bearing: `CREATE MATERIALIZED VIEW ... WITH
-- (timescaledb.continuous)` cannot run inside a transaction block, and a
-- multi-statement simple query is an implicit transaction. The runner
-- therefore sends this file one top-level statement per round trip; without
-- the directive PostgreSQL would reject every statement here with an error
-- that looks like a bug in the runner.
--
-- DELIBERATE DEVIATION from docs/04-data-model.md, stated here rather than
-- discovered later. docs/04 writes `avg(value) AS avg` at each level and chains
-- the levels. An average of averages is only correct when every bucket carries
-- the same number of points, which is exactly what a telemetry store cannot
-- promise: a vessel that drops off the air for forty minutes of an hour makes
-- the 1h `avg` of twenty 1m rows a lie about that hour. These views therefore
-- carry `sum_value` and `n` instead, and every level above 1m sums both -- so
-- `sum_value / n` is the exact mean at 15m, 1h and 1d, not an approximation of
-- one. The query builders in this package compute `avg` from those two columns;
-- consumers never see the difference except that the number is right.
--
-- SHADOW ROWS LIVE IN RAW ONLY. The 1m level aggregates
-- `installation_role = 0` -- the primary installation -- and nothing else. A
-- shadow installation exists to be compared against the primary, so folding
-- both into one bucket would produce a mean of two different instruments and
-- call it the vessel's value. Shadow history is readable in
-- `telemetry_numeric`; it is deliberately absent from every rollup level.
--
-- `timescaledb.materialized_only = true` is stated rather than inherited (it
-- has been the default since 2.13). Reads therefore see materialized buckets
-- only: each level lags by its `end_offset` plus up to one
-- `schedule_interval`, which the README states per level. A consumer needing
-- the current partial bucket reads raw.
--
-- APPLIED MIGRATIONS ARE IMMUTABLE. Add 000N+1; do not edit this file.

CREATE MATERIALIZED VIEW IF NOT EXISTS telemetry_numeric_1m
WITH (timescaledb.continuous, timescaledb.materialized_only = true) AS
  SELECT
    time_bucket(INTERVAL '1 minute', ts) AS bucket,
    vessel_id,
    series_id,
    count(*)         AS n,
    sum(value)       AS sum_value,
    min(value)       AS min_value,
    max(value)       AS max_value,
    last(value, ts)  AS last_value
  FROM telemetry_numeric
  WHERE installation_role = 0
  GROUP BY 1, 2, 3
WITH NO DATA;

CREATE MATERIALIZED VIEW IF NOT EXISTS telemetry_numeric_15m
WITH (timescaledb.continuous, timescaledb.materialized_only = true) AS
  SELECT
    time_bucket(INTERVAL '15 minutes', bucket) AS bucket,
    vessel_id,
    series_id,
    sum(n)                    AS n,
    sum(sum_value)            AS sum_value,
    min(min_value)            AS min_value,
    max(max_value)            AS max_value,
    last(last_value, bucket)  AS last_value
  FROM telemetry_numeric_1m
  GROUP BY 1, 2, 3
WITH NO DATA;

CREATE MATERIALIZED VIEW IF NOT EXISTS telemetry_numeric_1h
WITH (timescaledb.continuous, timescaledb.materialized_only = true) AS
  SELECT
    time_bucket(INTERVAL '1 hour', bucket) AS bucket,
    vessel_id,
    series_id,
    sum(n)                    AS n,
    sum(sum_value)            AS sum_value,
    min(min_value)            AS min_value,
    max(max_value)            AS max_value,
    last(last_value, bucket)  AS last_value
  FROM telemetry_numeric_15m
  GROUP BY 1, 2, 3
WITH NO DATA;

-- The 1d bucket is a UTC day. `time_bucket` without a timezone argument
-- buckets on UTC boundaries, so a "day" here is 00:00Z..24:00Z for every
-- vessel regardless of where it is. A product wanting local days reads 1h and
-- buckets in the query; it does not get them from this view.
CREATE MATERIALIZED VIEW IF NOT EXISTS telemetry_numeric_1d
WITH (timescaledb.continuous, timescaledb.materialized_only = true) AS
  SELECT
    time_bucket(INTERVAL '1 day', bucket) AS bucket,
    vessel_id,
    series_id,
    sum(n)                    AS n,
    sum(sum_value)            AS sum_value,
    min(min_value)            AS min_value,
    max(max_value)            AS max_value,
    last(last_value, bucket)  AS last_value
  FROM telemetry_numeric_1h
  GROUP BY 1, 2, 3
WITH NO DATA;

-- Refresh policies. `end_offset` keeps each refresh clear of the bucket still
-- being written.
--
-- `start_offset` is the window a scheduled refresh reconsiders, and it is 7
-- days at the two finest levels on purpose: the raw hypertable keeps 7 days
-- globally, and the edge is a store-and-forward uploader. A boat that was
-- offline for three days uploads three-day-old points into raw, and a 2-hour
-- `start_offset` would never look at the buckets they belong to -- the points
-- would sit in raw until the global window dropped them and never appear in
-- any rollup. 7 days is the whole raw window, so anything raw still holds can
-- still be materialized. A batch accepted outside even that window is the
-- consumer's to refresh explicitly: `refreshRollupsStatements({ range })`
-- from this package emits the `refresh_continuous_aggregate` call for it.
SELECT add_continuous_aggregate_policy('telemetry_numeric_1m',
  start_offset => INTERVAL '7 days',
  end_offset   => INTERVAL '1 minute',
  schedule_interval => INTERVAL '1 minute',
  if_not_exists => TRUE);

SELECT add_continuous_aggregate_policy('telemetry_numeric_15m',
  start_offset => INTERVAL '7 days',
  end_offset   => INTERVAL '15 minutes',
  schedule_interval => INTERVAL '15 minutes',
  if_not_exists => TRUE);

SELECT add_continuous_aggregate_policy('telemetry_numeric_1h',
  start_offset => INTERVAL '7 days',
  end_offset   => INTERVAL '1 hour',
  schedule_interval => INTERVAL '1 hour',
  if_not_exists => TRUE);

SELECT add_continuous_aggregate_policy('telemetry_numeric_1d',
  start_offset => INTERVAL '30 days',
  end_offset   => INTERVAL '1 day',
  schedule_interval => INTERVAL '1 hour',
  if_not_exists => TRUE);
