-- 0003_history_roles.sql -- the three roles docs/09-security-and-safety.md
-- fixes for Cloud <-> Postgres: ingest_writer, history_reader, ops.
--
-- They are NOLOGIN group roles and carry no password. An operator creates the
-- login user Hyperdrive authenticates as and grants it membership, so no
-- credential is ever in this repository, in a migration file, or in a deploy
-- log. That is the whole reason the roles are separated from the users.
--
-- Least privilege is expressed by what is absent:
--
--   ingest_writer   INSERT on the hypertables, INSERT+SELECT on series. No
--                   UPDATE, no DELETE, no TRUNCATE: a compromised ingest path
--                   can add wrong history but cannot erase the right history.
--   history_reader  SELECT on the tables and the aggregate views. Nothing else.
--                   The read path in a Worker uses this role.
--   ops             the retention and migration role: DDL, plus DELETE on the
--                   aggregates and track_points. Retention runs as ops, never
--                   as the writer.
--
-- APPLIED MIGRATIONS ARE IMMUTABLE. Add 000N+1; do not edit this file.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ingest_writer') THEN
    CREATE ROLE "ingest_writer" NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'history_reader') THEN
    CREATE ROLE "history_reader" NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ops') THEN
    CREATE ROLE "ops" NOLOGIN;
  END IF;
END
$$;

-- A statement deadline per role, applied at connection time rather than left
-- to each caller. The write path is a queue consumer with an ack budget; the
-- read path serves a request; ops runs a nightly sweep.
ALTER ROLE "ingest_writer"  SET statement_timeout = '15s';
ALTER ROLE "history_reader" SET statement_timeout = '30s';
ALTER ROLE "ops"            SET statement_timeout = '600s';

-- ingest_writer
GRANT USAGE ON SCHEMA "public" TO "ingest_writer";
GRANT SELECT ON "public"."series" TO "ingest_writer";
GRANT INSERT ON "public"."series" TO "ingest_writer";
GRANT INSERT ON "public"."telemetry_numeric" TO "ingest_writer";
GRANT INSERT ON "public"."track_points" TO "ingest_writer";
-- No sequence grant: series_id is GENERATED ALWAYS AS IDENTITY, whose sequence
-- is owned by the column and driven by the INSERT privilege above. A separate
-- USAGE grant would only add a hard-coded sequence name this file would have to
-- guess right, and identity is not `serial`.

-- history_reader
GRANT USAGE ON SCHEMA "public" TO "history_reader";
GRANT SELECT ON "public"."series" TO "history_reader";
GRANT SELECT ON "public"."telemetry_numeric" TO "history_reader";
GRANT SELECT ON "public"."track_points" TO "history_reader";
GRANT SELECT ON "public"."telemetry_numeric_1m" TO "history_reader";
GRANT SELECT ON "public"."telemetry_numeric_15m" TO "history_reader";
GRANT SELECT ON "public"."telemetry_numeric_1h" TO "history_reader";
GRANT SELECT ON "public"."telemetry_numeric_1d" TO "history_reader";

-- ops
GRANT USAGE ON SCHEMA "public" TO "ops";
GRANT CREATE ON SCHEMA "public" TO "ops";
GRANT SELECT, INSERT, UPDATE, DELETE ON "public"."series" TO "ops";
GRANT SELECT, INSERT, UPDATE, DELETE ON "public"."telemetry_numeric" TO "ops";
GRANT SELECT, INSERT, UPDATE, DELETE ON "public"."track_points" TO "ops";
GRANT SELECT, DELETE ON "public"."telemetry_numeric_1m" TO "ops";
GRANT SELECT, DELETE ON "public"."telemetry_numeric_15m" TO "ops";
GRANT SELECT, DELETE ON "public"."telemetry_numeric_1h" TO "ops";
GRANT SELECT, DELETE ON "public"."telemetry_numeric_1d" TO "ops";
