-- 0003_history_roles.sql -- the GRANT matrix for the three roles
-- docs/09-security-and-safety.md fixes for Cloud <-> Postgres: ingest_writer,
-- history_reader, ops.
--
-- GENERATED FROM `HISTORY_ROLE_PRIVILEGES` in src/timescale/roles.ts. Every
-- executable line below is exactly what `historyRoleGrantStatements()` emits,
-- and tests/migrations.test.ts asserts that equality -- so the library's grant
-- builder and this file cannot drift. Change the matrix in TypeScript and add
-- a new migration; do not hand-edit these lines.
--
-- THIS FILE DOES NOT CREATE ROLES AND DOES NOT SET TIMEOUTS. The target
-- instance's own initdb (narduk-infrastructure#155) creates ingest_writer,
-- history_reader and ops WITH LOGIN and sets each one's role-level
-- statement_timeout. Both need superuser, which the migration role is not;
-- an `ALTER ROLE ... SET statement_timeout` here would also have replaced the
-- deployment's 60 s with a library default and nothing would have reported it.
-- The deployment owns roles and timeouts; this migration owns privileges.
--
-- Least privilege is expressed by what is absent:
--
--   ingest_writer   INSERT on the hypertables, INSERT+SELECT on series. No
--                   UPDATE, no DELETE, no TRUNCATE: a compromised ingest path
--                   can add wrong history but cannot erase the right history.
--                   No sequence grant either: series_id is GENERATED ALWAYS AS
--                   IDENTITY, whose sequence is owned by the column and driven
--                   by the INSERT privilege.
--   history_reader  SELECT on the tables and the four rollup views. Nothing
--                   else. The read path in a Worker uses this role.
--   ops             migrations and retention: DDL plus row mutation on the
--                   three base tables. It gets SELECT but not DELETE on the
--                   continuous aggregates -- rollup retention is a time-based
--                   drop_chunks on the materialization hypertable, an owner
--                   operation, so a DELETE grant on the view would only have
--                   looked like the thing doing the work.
--
-- APPLIED MIGRATIONS ARE IMMUTABLE. Add 000N+1; do not edit this file.

GRANT USAGE ON SCHEMA "public" TO "ingest_writer";
GRANT SELECT ON "public"."series" TO "ingest_writer";
GRANT INSERT ON "public"."series" TO "ingest_writer";
GRANT INSERT ON "public"."telemetry_numeric" TO "ingest_writer";
GRANT INSERT ON "public"."track_points" TO "ingest_writer";
GRANT USAGE ON SCHEMA "public" TO "history_reader";
GRANT SELECT ON "public"."series" TO "history_reader";
GRANT SELECT ON "public"."telemetry_numeric" TO "history_reader";
GRANT SELECT ON "public"."track_points" TO "history_reader";
GRANT SELECT ON "public"."telemetry_numeric_1m" TO "history_reader";
GRANT SELECT ON "public"."telemetry_numeric_15m" TO "history_reader";
GRANT SELECT ON "public"."telemetry_numeric_1h" TO "history_reader";
GRANT SELECT ON "public"."telemetry_numeric_1d" TO "history_reader";
GRANT USAGE ON SCHEMA "public" TO "ops";
GRANT CREATE ON SCHEMA "public" TO "ops";
GRANT SELECT ON "public"."series" TO "ops";
GRANT SELECT ON "public"."telemetry_numeric" TO "ops";
GRANT SELECT ON "public"."track_points" TO "ops";
GRANT SELECT ON "public"."telemetry_numeric_1m" TO "ops";
GRANT SELECT ON "public"."telemetry_numeric_15m" TO "ops";
GRANT SELECT ON "public"."telemetry_numeric_1h" TO "ops";
GRANT SELECT ON "public"."telemetry_numeric_1d" TO "ops";
GRANT INSERT ON "public"."series" TO "ops";
GRANT INSERT ON "public"."telemetry_numeric" TO "ops";
GRANT INSERT ON "public"."track_points" TO "ops";
GRANT UPDATE, DELETE ON "public"."series" TO "ops";
GRANT UPDATE, DELETE ON "public"."telemetry_numeric" TO "ops";
GRANT UPDATE, DELETE ON "public"."track_points" TO "ops";
